server {
    listen 3202 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    client_max_body_size 11m;

    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=5s ipv6=off;
    set $server_upstream server:3202;

    location /api/ {
        proxy_pass https://$server_upstream$request_uri;
        proxy_http_version 1.1;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location = /health {
        proxy_pass https://$server_upstream$request_uri;
        proxy_http_version 1.1;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location ~ ^/default-avatar(-100|-300)?\.(png|svg)$ {
        add_header Cache-Control "max-age=86400";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
