{
 "title": "GophProfile Go Runtime",
 "tags": [
  "goph-profile",
  "go-runtime"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (go_goroutine_count{job=~\"goph-profile-.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (go_memory_used_bytes{job=~\"goph-profile-.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go GC goal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (go_memory_gc_goal_bytes{job=~\"goph-profile-.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go processor limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (go_processor_limit{job=~\"goph-profile-.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}