apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "goph-profile.fullname" . }}-server
  labels:
    {{- include "goph-profile.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- if .Values.ingress.rateLimit.enabled }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: >-
      {{ include "goph-profile.rateLimitMiddlewareReference" . }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "goph-profile.ingressTLSSecretName" . }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "goph-profile.fullname" . }}-server
                port:
                  number: {{ .Values.server.service.port }}
