{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "goph-profile.migrateName" . }}
  labels:
    {{- include "goph-profile.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  podSelector:
    matchLabels:
      {{- include "goph-profile.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: migrate
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace | quote }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podSelector | nindent 14 }}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - ports:
        - port: {{ .Values.networkPolicy.ports.database }}
          protocol: TCP
{{- end }}
