apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goph-profile.tlsSecretName" . }}
  labels:
    {{- include "goph-profile.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |-
    {{- .Values.tls.certificate | trim | nindent 4 }}
  tls.key: |-
    {{- .Values.tls.privateKey | trim | nindent 4 }}
