apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goph-profile.secretName" . }}
  labels:
    {{- include "goph-profile.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOPH_PROFILE_DATABASE_URI: {{ .Values.secret.databaseURI | quote }}
  GOPH_PROFILE_FILE_STORAGE_ACCESS_KEY: {{ .Values.secret.fileStorageAccessKey | quote }}
  GOPH_PROFILE_FILE_STORAGE_SECRET_KEY: {{ .Values.secret.fileStorageSecretKey | quote }}
  GOPH_PROFILE_QUEUE_URL: {{ .Values.secret.queueURL | quote }}
