apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goph-profile.fullname" . }}-worker
  labels:
    {{- include "goph-profile.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
