{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goph-profile.otelCollectorName" . }}
  labels:
    {{- include "goph-profile.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: {{ .Values.otelCollector.ports.otlpGrpc }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.otelCollector.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "goph-profile.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
{{- end }}
